### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Dkakuma00** [Autodesk/cam-posteditor#51] opened 2023-01-03 11:34 UTC
Hello, 
I want to start editting my post processor and i get an error message:
Error running command propertyList.initializePropertyList: command 'propertyList.initializePropertyList' not found. This is likely caused by the extension that contributes propertyList.initializePropertyList.

Also in the extension exploler I cant select anything. All folders ara empty
![image](https://user-images.githubusercontent.com/121867134/210349540-14909de4-3309-4d1b-b2d8-a522aa2c477c.png)

**Comment by cpsdev** [comment] 2023-01-03 16:18
Hello @Dkakuma00 ,
thanks for your feedback. This was a known issue and it is fixed with version 4.1.2 which just has been released.
Please let me know if the problem is solved with the updated version.

Thank you,
Achim

**Closed** 2024-03-11 11:25 UTC
